import os

Import('env')

_INCLUDES = [Dir('../src').abspath]
if env['PLATFORM'] == 'darwin':
	_INCLUDES += [Dir('../include/macosx').abspath]

_SOURCES = ['OscServer.cpp', 'OscClient.cpp']
_SOURCES = [File('../src/' + s).abspath for s in _SOURCES]

_LIBS = ['liblo.a']
if env['PLATFORM'] == 'darwin':
	_LIBS = [Dir('../lib/macosx/').abspath + '/' + s for s in _LIBS]
else:
	_LIBS = []
_LIBS = [File(s) for s in _LIBS]

env.Append(APP_SOURCES = _SOURCES)
env.Append(CPPPATH = _INCLUDES)
env.Append(LIBS = _LIBS)

Return('env')
